name: Kyle Jackson
favicon: null
layout_spectrum: 0.27287
typography_spectrum: 0.36745
title: Kyle Jackson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#958d83'
    - '#d0c4b9'
    - '#534837'
  brandStrength: 0.8621261736843735
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
