name: Kyle Jackson
favicon: null
layout_spectrum: 0.09659235156141222
typography_spectrum: 0.5766272572800517
title: Kyle Jackson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8621261736843735
  lightness: 0.9825684046372771
  saturation: 0.515899371355772
  rhythmicContrast: 0.18109141965396702
purpose: []
