title: Kyle Jackson
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#BED8E9'
    - '#2F2827'
    - '#646366'
    - '#FBC4A4'
    - '#E9384C'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Kyle Jackson
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7094522
layout_spectrum: 0.7051557
