title: Kyle Jackson
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.29885248141363263
  brandStrength: 0.934993629110977
  lightness: 0.9660046698991209
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  rhythmicContrast: 0.4119838650804013
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Kyle Jackson
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8547480790875852
layout_spectrum: 0.14176783268339932
